### ISSUE TITLE
alias

### ISSUE THREAD

**Issue by Megan-TA** [Lucifier129/react-imvc#10]
外部config配置alias选项传入
 比如 "@main: path.resolve(__dirname, 'src/main')" 
组件引用main路径 import Main from “@main”
会提示@main找不到 报错的问题

**Comment by Lucifier129** [comment]
config 的 alias 目前只能配置 package.json 里的依赖，比如把 react 配置成 preact-compat/react-lite 什么的。

暂时不支持配置一个自定义的，因为 node.js 运行时，会找不到这个模块（node.js 运行时没有 webpack）
