### ISSUE TITLE
devtools缺省建议换成cheap-module-source-map

### ISSUE THREAD

**Issue by liyikun** [Lucifier129/react-imvc#16]
devtool = 'cheap-module-source-map'

之前的缺省配置会出现在一些chrome下会出现断点打的不准，

**Comment by Lucifier129** [comment]
有什么资料可以说明 `cheap-module-source-map` 更准确吗？

**Comment by liyikun** [comment]
> 有什么资料可以说明 `cheap-module-source-map` 更准确吗？
> 
> 可以通过 `imvc.config.js` 里配置 [devtool](https://github.com/Lucifier129/react-imvc/blob/master/config/config.defaults.js#L121) 来实现。

目前我是通过imvconfig来修改配置了，只是建议改下缺省

**Comment by Lucifier129** [comment]
LGTM，建议提个PR过来

**Comment by liyikun** [comment]
> LGTM，建议提个PR过来

https://github.com/Lucifier129/react-imvc/pull/17
