### ISSUE TITLE
build/setup-dev-env.js 中 setupServer 读取的配置文件是client端

### ISSUE THREAD

**Issue by liyikun** [Lucifier129/react-imvc#23]
`exports.setupServer = function setupServer(config, options) {
	let serverConfig = createWebpackConfig(config)`

这里第二个 参数不传 里面isserver就是false 

/build/createWebpackConfig.js

最下面 return config.webpack ? config.webpack(result, isServer) : result 这里就不对啊

**Comment by liyikun** [comment]
这里配置文件还是略奇怪，，我都晕了， setupServer 里面又重写了部分config 让dev server可用，，

**Comment by liyikun** [comment]
我的需求是 在imvc.config 的配置里面 根据环境 处理一些非js的loader时候 用webpack的 ignore loader处理下

**Comment by Lucifier129** [comment]
已处理此问题，关闭 Issue
