### ISSUE TITLE
请问怎么引用less和外部的js文件，具体在哪里配置呢

### ISSUE THREAD

**Issue by chenpengjun** [Lucifier129/react-imvc#8]

**Comment by Lucifier129** [comment]
目前暂时不支持 import 不是 js 文件的模块。只支持 js 模块，这样才能在 node 里运行，实现同构。

**Comment by AttackXiaoJinJin** [comment]
> 目前暂时不支持 import 不是 js 文件的模块。只支持 js 模块，这样才能在 node 里运行，实现同构。

所以css-in-js这种直接把样式写进js文件的，是天然契合imvc吗？

**Comment by Lucifier129** [comment]
@AttackXiaoJinJin  一般的 css-in-js 是 browser-side runtime 里动态 append style，不好做 SSR。

像 tailwind-css/vanilla-extract 这类在 build-time 生成 css 文件的则没有这类问题。

此外，最新版本的 react-imvc 可以 import css file，不过拿到的不是 style content，而是 style url，配合 publicPath 可以拼接出 style 地址。

```ts
// style 是一个 string，会在构建后带上 hash 值
import style from './style.css'

export class Home extends Controller {
  preload = {
    style: style
  }
}
```
